language: php
php:
  - "5.4"
  - "5.3"
notifications:
  email: false
before_script:
  - "cp -r dependencies/include/* newscoop/include/"
  - cd newscoop/
  - composer self-update
  - composer install
  - php scripts/doctrine.php
