parameters:
    phpSettings:
        display_startup_errors: "0"
        display_errors: "0"
    includePaths:
        library: "%application_path%/../library"
    bootstrap:
        path: "%application_path%/Bootstrap.php"
        class: "Bootstrap"
    appnamespace: "Application"
    resources:
        frontController:
            controllerDirectory: "%application_path%/controllers"
            params:
                displayExceptions: "0"
            moduleDirectory: "%application_path%/modules"
            actionHelperPaths:
                Action_Helper: "%application_path%/controllers/helpers"
        layout:
            layoutPath: "%application_path%/layouts/scripts/"
        view: ""        
        modules: 
            - ""
    pluginPaths:
        Resource: "%application_path%/../library/Resource"
    session:
        cookie_path: "/"
    translation:
        path: "%application_path%/languages"
    doctrine:
        cache: "array"
        entity:
            dir: "%application_path%/../library/Newscoop"
        proxy:
            dir: "%application_path%/../library/Proxy"
            namespace: "Proxy"
            autogenerate: false
        functions:
            rand: "Newscoop\Query\MysqlRandom"
            dayofweek: "Newscoop\Query\MysqlDayOfWeek"
            dayofmonth: "Newscoop\Query\MysqlDayOfMonth"
            dayofyear: "Newscoop\Query\MysqlDayOfYear"
            date_format: "Newscoop\Query\MysqlDateFormat"
    admin:
        resources:
            layout:
                jsUrl: "/js/app/admin"
                jsPath: "%application_path%/../js/app/admin"
                layout: "admin"
            acl:
                modules:
                    - "admin"
                cache: "Doctrine\Common\Cache\ArrayCache"
            view: ""
    autoloader:
        dirs:
            - "%application_path%/../classes"
            - "%application_path%/../classes/Extension"
            - "%application_path%/../template_engine/classes"
            - "%application_path%/../template_engine/metaclasses"
    resourceNames:
        Aliases: "alias"
        ArticleAttachments: "article-attachment"
        ArticleAuthors: "article-author"
        ArticleImages: "article-image"
        ArticlePublish: "article-publish"
        Articles: "article"
        ArticleTopics: "article-topic"
        ArticleTypeMetadata: "article-metadata"
        Attachments: "attachment"
        AuditEvent: "audit-event"
        AuthorAliases: "author-alias"
        AuthorBiographies: "author-biography"
        Authors: "author"
        AuthorTypes: "author-type"
        Countries: "county"
        Images: "image"
        Issues: "issue"
        Languages: "language"
        Locations: "location"
        Maps: "map"
        Plugins: "plugin"
        Publication: "publication"
        Sections: "section"
        Subscriptions: "subscription"
        SystemPreferences: "system-preferences"
        Templates: "template"
        Topics: "topic"
        Translations: "translation"
    auth:
        modules:
            - "admin"
        ignore:
            - "auth"
            - "error"
            - "legacy"
            - "login.php"
            - "password_recovery.php"
            - "password_check_token.php"
    acl:
        modules:
            - "admin"
        ignore:
            - "auth"
            - "error"
            - "legacy"
            - "login.php"
            - "password_recovery.php"
            - "password_check_token.php"
    email:
        from: "no-reply@domain.com"
        contact: "info@domain.com"
    ingest:
        path: ""
    ingest_publisher:
        article_type: "newswire"
        section_other: "20"
        field:
            NewsItemIdentifier: "getNewsItemId"
            NewsProduct: "getProduct"
            Status: "getStatus"
            Urgency: "getPriority"
            HeadLine: "getTitle"
            NewsLineText: "getCatchLine"
            DataLead: "getSummary"
            DataContent: "getContent"
            AuthorNames: "getAuthors"
        image_path: ""
    blog:
        role: "6"
        publication: "5"
        issue: "3"
        type: "bloginfo"
        article_type: "blog"
    image:
        image_path: "%application_path%/../images/"
        image_prefix: "cms-image-"
        thumbnail_path: "%application_path%/../images/thumbnails/"
        thumbnail_prefix: "cms-thumb-"
        thumbnail_max_size: "64"
        cache_url: "images/cache"
        cache_path: "%application_path%/../images/cache/"
    attachment:
        file_base_url: "files/"
        file_directory: "%application_path%/../public/files/"
        file_num_dirs_level_1: 1000
        file_num_dirs_level_2: 1000
    search:
        solr_server: "http://localhost:8983/solr"
    subscriptions.service.class: "Newscoop\Services\SubscriptionService"
