parameters:
    admin:
        resources:
            acl:
                cache: "Doctrine\Common\Cache\ArrayCache"
    doctrine:
        cache: "array"
    phpSettings:
        display_startup_errors: "1"
        display_errors: "1"
    resources:
        frontController:
            params:
                displayExceptions: "1"
    session:
        cookie_domain: ""
    jobby:
        environment: 'dev'
