parameters:
    admin:
        resources:
            acl:
                cache: "Doctrine\Common\Cache\ArrayCache"
    audit:
        events: false
    community_feed:
        events: false
    doctrine:
        cache: "Doctrine\Common\Cache\ArrayCache"
        proxy:
            autogenerate: true
        database:
            driver: "pdo_sqlite"
            path: ":memory:"
        functions:
            rand: "Newscoop\Query\SqliteRandom"
    ingest:
        path: %application_path%/../tests/ingest
    ingest_publisher:
        image_path: %application_path%/../tests/ingest
        article_type: "news"
        field.NewsItemIdentifier: false
        field.NewsProduct: false
        field.Status: false
        field.Urgency: false
        field.HeadLine: false
        field.NewsLineText: false
        field.DataContent: false
        field.DataLead: false
        field.AuthorNames: false
        field.deck: "getSummary"
        field.full_text: "getContent"
    phpSettings:
        display_startup_errors: true
        display_errors: true
    resources:
        frontController:
            params:
                displayExceptions: true
