services:
    newscoop_newscoop.listener.authentication.backend.session:
        class: Newscoop\NewscoopBundle\EventListener\AuthenticationListener
        arguments:  ["@user", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    newscoop_newscoop.routing.loader.plugins:
        class: Newscoop\NewscoopBundle\Routing\PluginsLoader
        arguments: ["@newscoop.plugins.manager", "@service_container"]
        tags:
            - { name: routing.loader }

    newscoop_newscoop.doctrine.event_dispatcher_proxy:
        class: Newscoop\Doctrine\EventDispatcherProxy
        arguments: ["@event_dispatcher"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    newscoop_newscoop.menu_builder:
        class: %newscoop_newscoop.menu_builder.class%
        arguments: ["@knp_menu.factory", "@service_container"]

    newscoop_newscoop.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: newscoop_newscoop.menu_builder
        factory_method: mainMenu
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    newscoop_newscoop.menu.main_modern:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: newscoop_newscoop.menu_builder
        factory_method: mainMenu
        arguments:
            - true
        tags:
            - { name: knp_menu.menu, alias: main_modern } # The alias is what is used to retrieve the menu

    newscoop_newscoop.menu.breadcrumb:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: newscoop_newscoop.menu_builder
        factory_method: mainBreadcrumb
        tags:
            - { name: knp_menu.menu, alias: breadcrumb } # The alias is what is used to retrieve the menu

    newscoop_newscoop.twig.newscoop_extension:
        class: Newscoop\NewscoopBundle\Twig\NewscoopExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    newscoop_newscoop.twig.include_as_verbatim_extension:
        class: Newscoop\NewscoopBundle\Twig\IncludeAsVerbatimExtension
        tags:
            - { name: twig.extension }

    newscoop_newscoop.password_encoder:
        class: Newscoop\NewscoopBundle\Security\Encoder\NewscoopPasswordEncoder

    newscoop_newscoop.security.authentication.success_handler:
        class: %newscoop_newscoop.security.authentication.success_handler.class%
        public: false
        arguments:  ['@security.http_utils', {}, '@auth.adapter', '@em']

    newscoop_newscoop.security.authentication.frontend.success_handler:
        class: %newscoop_newscoop.security.authentication.frontend.success_handler.class%
        public: false
        arguments:  ['@security.http_utils', {}, '@auth.adapter']

    newscoop_newscoop.listener.locale_listener:
        class: Newscoop\NewscoopBundle\EventListener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
        arguments:  ['@em']

    newscoop_newscoop.listener.route_listener:
        class: Newscoop\NewscoopBundle\EventListener\RouteListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 30 }
        arguments:  ['@newscoop.listpaginator.service']

    newscoop_newscoop.listener.no_cache_listener:
        class: Newscoop\NewscoopBundle\EventListener\NoCacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }

    newscoop_newscoop.translation_listener:
        class: Newscoop\NewscoopBundle\EventListener\OldPluginsTranslationListener
        arguments:  ['@translator', '@newscoop.cache', '@newscoop.plugins.service']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    system_preferences_service:
        class: Newscoop\NewscoopBundle\Services\SystemPreferencesService
        arguments:  ['@em']

    newscoop_newscoop.translation_template_listener:
        class: Newscoop\NewscoopBundle\EventListener\TemplateTranslationListener
        arguments:  ['@translator', '@newscoop.cache']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    newscoop_newscoop.session.storage:
        class:     %newscoop_newscoop.session.storage.class%
        arguments: [%session.storage.options%]

    newscoop_newscoop.criteria.users:
        class: Newscoop\User\UserCriteria

    newscoop_newscoop.template_lists.users:
        class:      Newscoop\TemplateList\UsersList
        arguments:  ["@newscoop_newscoop.criteria.users"]
        tags:
            -  { name: newscoop.template_lists }

    newscoop_newscoop.list_objects.listener:
        class: Newscoop\NewscoopBundle\EventListener\ListObjectsListener
        tags:
          - { name: kernel.event_listener, event: newscoop.listobjects.register, method: registerObjects }

    newscoop_newscoop.publication_service:
        class: Newscoop\Services\PublicationService
        arguments:  ["@em"]

    newscoop_newscoop.listener.publication:
        class: Newscoop\NewscoopBundle\EventListener\PublicationListener
        arguments:  ["@newscoop_newscoop.publication_service"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    newscoop_newscoop.listener.userip:
        class: Newscoop\NewscoopBundle\EventListener\UserIpListener
        arguments:  ["@user"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    newscoop_newscoop.article_service:
        class: Newscoop\Services\ArticleService
        arguments:  ["@em"]

    newscoop_newscoop.listener.article:
        class: Newscoop\NewscoopBundle\EventListener\ArticleListener
        arguments:  ["@newscoop_newscoop.article_service"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }

parameters:
    smarty.extension.routing.class: "Newscoop\\NewscoopBundle\\Extension\\RoutingExtension"
    smarty.extension.assetic.dynamic.class: "Newscoop\\NewscoopBundle\\Extension\\DynamicAsseticExtension"
    smarty.extension.assetic.static.class: "Newscoop\\NewscoopBundle\\Extension\\StaticAsseticExtension"
    newscoop_newscoop.security.authentication.success_handler.class: "Newscoop\\NewscoopBundle\\Security\\Http\\Authentication\\AuthenticationSuccessHandler"
    newscoop_newscoop.security.authentication.frontend.success_handler.class: "Newscoop\\NewscoopBundle\\Security\\Http\\Authentication\\AuthenticationFrontendSuccessHandler"
    security.authentication.failure_handler.class: "Newscoop\\NewscoopBundle\\Security\\Http\\Authentication\\AuthenticationFailedHandler"
    security.logout.success_handler.class: "Newscoop\\NewscoopBundle\\Security\\Http\\Authentication\\LogoutSuccessHandler"
    security.authentication.listener.form.class: "Newscoop\\NewscoopBundle\\EventListener\\CaptchaUsernamePasswordFormAuthenticationListener"
    newscoop_newscoop.menu_builder.class: "Newscoop\\NewscoopBundle\\Menu\\Builder"
    newscoop_newscoop.session.storage.class: "Newscoop\\NewscoopBundle\\Session\\Storage"
    ewz_recaptcha.form.type.class: "Newscoop\\NewscoopBundle\\Form\\Type\\RecaptchaType"
