Newscoop\Entity\Comment:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            read_only: true
            type: integer
            groups: ["details", "list"]
            serialized_name: id
        subject:
            expose: true
            read_only: true
            type: string
            groups: ["details", "list"]
            serialized_name: subject
        message:
            expose: true
            read_only: true
            type: string
            groups: ["details", "list"]
            serialized_name: message
        time_created:
            expose: true
            read_only: true
            type: DateTime
            groups: ["details", "list"]
            serialized_name: created
        commenter:
            expose: true
            read_only: true
            groups: ["details", "list"]
            type: string
            accessor: 
                getter: getCommenterName
                setter: setCommenterName
            serialized_name: author
        parent:
            expose: true
            read_only: true
            type: integer
            accessor: 
                getter: getParentId
            groups: ["details", "list"]
            serialized_name: parent
        thread_level:
            expose: true
            read_only: true
            type: integer
            groups: ["details", "list"]
            serialized_name: thread_level
        thread_order:
            expose: true
            read_only: true
            type: integer
            groups: ["details", "list"]
            serialized_name: thread_order