services:
    audit:
        class:      Newscoop\Services\AuditService
        arguments:  ["@em", "@user"]
        tags:
            -  { name: kernel.event_listener, event: comment.update, method: update }
            -  { name: kernel.event_listener, event: comment.delete, method: update }
            -  { name: kernel.event_listener, event: alias.create, method: update }
            -  { name: kernel.event_listener, event: alias.update, method: update }
            -  { name: kernel.event_listener, event: alias.delete, method: update }
            -  { name: kernel.event_listener, event: article-attachment.create, method: update }
            -  { name: kernel.event_listener, event: article-attachment.delete, method: update }
            -  { name: kernel.event_listener, event: article-author.create, method: update }
            -  { name: kernel.event_listener, event: article-author.delete, method: update }
            -  { name: kernel.event_listener, event: article-image.create, method: update }
            -  { name: kernel.event_listener, event: article-image.delete, method: update }
            -  { name: kernel.event_listener, event: article-publish.create, method: update }
            -  { name: kernel.event_listener, event: article.create, method: update }
            -  { name: kernel.event_listener, event: article.delete, method: update }
            -  { name: kernel.event_listener, event: article-topic.attach, method: update }
            -  { name: kernel.event_listener, event: article-topic.detach, method: update }
            -  { name: kernel.event_listener, event: article-metadata.create, method: update }
            -  { name: kernel.event_listener, event: article-metadata.delete, method: update }
            -  { name: kernel.event_listener, event: attachment.create, method: update }
            -  { name: kernel.event_listener, event: attachment.delete, method: update }
            -  { name: kernel.event_listener, event: author-alias.create, method: update }
            -  { name: kernel.event_listener, event: author-alias.delete, method: update }
            -  { name: kernel.event_listener, event: author-biography.create, method: update }
            -  { name: kernel.event_listener, event: author-biography.delete, method: update }
            -  { name: kernel.event_listener, event: author.create, method: update }
            -  { name: kernel.event_listener, event: author.delete, method: update }
            -  { name: kernel.event_listener, event: author-type.create, method: update }
            -  { name: kernel.event_listener, event: author-type.delete, method: update }
            -  { name: kernel.event_listener, event: county.create, method: update }
            -  { name: kernel.event_listener, event: county.delete, method: update }
            -  { name: kernel.event_listener, event: image.create, method: update }
            -  { name: kernel.event_listener, event: image.delete, method: update }
            -  { name: kernel.event_listener, event: localimage.create, method: update }
            -  { name: kernel.event_listener, event: localimage.delete, method: update }
            -  { name: kernel.event_listener, event: issue.create, method: update }
            -  { name: kernel.event_listener, event: issue.delete, method: update }
            -  { name: kernel.event_listener, event: language.create, method: update }
            -  { name: kernel.event_listener, event: language.delete, method: update }
            -  { name: kernel.event_listener, event: location.create, method: update }
            -  { name: kernel.event_listener, event: location.delete, method: update }
            -  { name: kernel.event_listener, event: map.create, method: update }
            -  { name: kernel.event_listener, event: map.delete, method: update }
            -  { name: kernel.event_listener, event: plugin.create, method: update }
            -  { name: kernel.event_listener, event: plugin.delete, method: update }
            -  { name: kernel.event_listener, event: publication.create, method: update }
            -  { name: kernel.event_listener, event: publication.delete, method: update }
            -  { name: kernel.event_listener, event: section.create, method: update }
            -  { name: kernel.event_listener, event: section.delete, method: update }
            -  { name: kernel.event_listener, event: subscription.create, method: update }
            -  { name: kernel.event_listener, event: subscription.delete, method: update }
            -  { name: kernel.event_listener, event: system-preferences.create, method: update }
            -  { name: kernel.event_listener, event: system-preferences.delete, method: update }
            -  { name: kernel.event_listener, event: template.create, method: update }
            -  { name: kernel.event_listener, event: template.delete, method: update }
            -  { name: kernel.event_listener, event: topic.create, method: update }
            -  { name: kernel.event_listener, event: topic.delete, method: update }
            -  { name: kernel.event_listener, event: translation.create, method: update }
            -  { name: kernel.event_listener, event: translation.delete, method: update }
