services:
    newscoop_doctrine:
        class:      Newscoop\Doctrine\Doctrine
        arguments:  ["%doctrine%"]
    newscoop_doctrine_connection:
        class:      Doctrine\DBAL\Connection
        factory_service:  newscoop_doctrine
        factory_method:   getConnection
    newscoop_doctrine_entityManager:
        class:      Doctrine\ORM\EntityManager
        factory_service:  newscoop_doctrine
        factory_method:   getEntityManager
    doctrine:
        class:      Newscoop\Doctrine\Registry
        arguments:
            - "@service_container"
            - newscoop: "newscoop_doctrine_connection"
            - newscoop: "newscoop_doctrine_entityManager"
            - newscoop
            - newscoop
    doctrine.em:
        class:      Doctrine\ORM\EntityManager
        factory_service:  doctrine
        factory_method:   getEntityManager
        arguments:
            - newscoop
    em:
        alias: doctrine.em
    doctrine.event_manager:
        class:      Doctrine\Common\EventManager
        factory_service:  doctrine.em
        factory_method:   getEventManager
    newscoop.doctrine.event_dispatcher_proxy:
        class: Newscoop\Doctrine\EventDispatcherProxy
        arguments:  ["@event_dispatcher"]
    doctrine.event_subscriber:
        class:      Doctrine\Common\EventSubscriber
        factory_service:  doctrine.event_manager
        factory_method:   addEventSubscriber
        arguments:  ["@newscoop.doctrine.event_dispatcher_proxy"]
    doctrine.connection:
        class: Doctrine\DBAL\Connection
        factory_service: doctrine.em
        factory_method: getConnection
    doctrine.adodb:
        class:      Newscoop\Doctrine\AdoDbAdapter
        arguments:  ["@doctrine.connection"]
    image:
        class:      Newscoop\Image\ImageService
        arguments:  ["%image%", "@em"]
    zend_auth:
        class:      Zend_Auth
        factory_class: Zend_Auth
        factory_method: getInstance
    event_dispatcher:
        class:      Newscoop\EventDispatcher\EventDispatcher
        arguments:  ["@service_container"]
    dispatcher:
        alias: event_dispatcher
    user:
        class:      Newscoop\Services\UserService
        arguments:  ["@em", "@zend_auth"]
    user.list:
        class:      Newscoop\Services\ListUserService
        arguments:  ["%blog%", "@em"]
    user.token:
        class:      Newscoop\Services\UserTokenService
        arguments:  ["@em"]
    user_type:
        class:      Newscoop\Services\UserTypeService
        arguments:  ["@em"]
    author:
        class:      Newscoop\Services\AuthorService
        arguments:  ["@em"]
    audit.maintenance:
        class:      Newscoop\Services\AuditMaintenanceService
        arguments:  ["@em"]
    user.topic:
        class:      Newscoop\Services\UserTopicService
        arguments:  ["@em", "@event_dispatcher"]
    auth.adapter:
        class:      Newscoop\Services\Auth\DoctrineAuthService
        arguments:  ["@em"]
    auth.adapter.social:
        class:      Newscoop\Services\Auth\SocialAuthService
        arguments:  ["@em"]
    email:
        class:      Newscoop\Services\EmailService
        arguments:  ["%email%", "@view", "@user.token"]
    ingest.publisher:
        class:      Newscoop\Services\Ingest\PublisherService
        arguments:  ["%ingest_publisher%"]
    ingest:
        class:      Newscoop\Services\IngestService
        arguments:  ["%ingest%", "@em", "@ingest.publisher"]
    blog:
        class:      Newscoop\Services\BlogService
        arguments:  ["%blog%"]
    user.search:
        class:      Newscoop\Services\UserSearchService
        arguments:  ["@em"]
    content.publication:
        class:      Newscoop\Content\PublicationService
        arguments:  ["@em"]
    content.section:
        class:      Newscoop\Content\SectionService
        arguments:  ["@em"]
    content.type:
        class:      Newscoop\Content\ContentTypeService
        arguments:  ["@em"]
    stat:
        class:      Newscoop\Services\StatService
        arguments:  ["@em"]
    view:
        class:      Newscoop\View\ViewFactory
        factory_class:  Newscoop\View\ViewFactory
        factory_method:   getView
    view.helper.thumbnail:
        class:      Newscoop\Image\ThumbnailViewHelper
        arguments:  ["@image"]
    view.helper.rendition:
        class:      Newscoop\Image\RenditionViewHelper
        arguments:  ["@image"]
    image.rendition:
        class:      Newscoop\Image\RenditionService
        arguments:  ["%rendition%", "@em", "@image"]
    image.search:
        class:      Newscoop\Image\ImageSearchService
        arguments:  ["@em"]
    package:
        class:      Newscoop\Package\PackageService
        arguments:  ["@em", "@image"]
    package.search:
        class:      Newscoop\Package\PackageSearchService
        arguments:  ["@em"]
    zend_router:
        class:      Newscoop\Router\RouterFactory
        factory_class:  Newscoop\Router\RouterFactory
        factory_method: initRouter
        arguments:  ["@service_container"]
    subscription:
        class:      Newscoop\Subscription\SubscriptionFacade
        arguments:  ["@em"]
    subscription.section:
        class:      Newscoop\Subscription\SectionFacade
        arguments:  ["@em"]
    subscription.ip:
        class:      Newscoop\Subscription\IpFacade
        arguments:  ["@em"]
    subscription.service:
        class:      Newscoop\Services\SubscriptionService
        arguments:  ["@em"]
    random:
        class:      Newscoop\Random
    webcode:
        class:      Newscoop\WebcodeFacade
        arguments:  ["@em", "@random"]
    storage.adapter:
        class:      Zend_Cloud_StorageService_Adapter_FileSystem
        arguments:  ["%storage%"]
    storage:
        class:      Newscoop\Storage\StorageService
        arguments:  ["@storage.adapter"]
    image.update_storage:
        class:      Newscoop\Image\UpdateStorageService
        arguments:  ["@em", "@storage"]
    notification:
        class:      Newscoop\Services\NotificationService
        arguments:  ["@em"]
    topic:
        class: Newscoop\Topic\TopicService
        arguments: ["@em"]
    http.client.factory:
        class: Newscoop\Http\ClientFactory
    search.index:
        class: Newscoop\Search\SolrIndex
        arguments: ["@http.client.factory", "%search%"]
    search.indexer.article:
        class: Newscoop\Search\ArticleIndexer
        arguments: ["@em", "@search.index"]
    preferences:
        class: SystemPref
    mailchimp.api.factory:
        class: Newscoop\MailChimp\ApiFactory
        arguments: ["@preferences"]
    mailchimp.list:
        class: Newscoop\MailChimp\ListApi
        arguments: ["@mailchimp.api.factory", "@preferences"]
    plugins.manager:
        class: Newscoop\Services\PluginsManagerService
        arguments: ["@em", "@event_dispatcher"]

