_profiler:
    resource: @WebProfilerBundle/Resources/config/routing/profiler.xml
    prefix:   /_profiler

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix: /_wdt

_main:
    resource: routing.yml